spring.application.name=currency-api

app.exchangerate.api-key=2c297772afc857652b0b738e
app.exchangerate.base-url=https://v6.exchangerate-api.com/v6

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

server.port=8080